### ISSUE TITLE
Tests don't run on jspm/jasmine setup

### ISSUE THREAD

**Issue by jabhishek** [jdlehman/alt-example-tests#3]
Hi,

I am working on application using Alt and was trying to setup tests based on this repo. I tried to setup the tests in exactly the same way but in jspm/karma/jasmine setup, but wasn't able to make them pass. Then, I copied pasted your code and tried to run the tests in my setup but surprisingly even they didn't work. I have setup a repository with the test on github [here](https://github.com/jabhishek/alt-es6-tests-example).

Probably I am doing something stupid, but I have spend hours on this and couldn't find the problem. I would appreciate any help on this.

Thanks,
Abhi.

**Comment by jdlehman** [comment]
It looks like the problem is the difference with how jspm handles modules.  If you put a console log in `MyAlt.js` you will see that it gets logged multiple times when being handled by jspm, whereas with webpack it only gets called once because of how webpack resolves the requires versus how jspm does.  This means that each time you `import alt from 'MyAlt';`, you are getting a whole new alt instance.  So the test is dispatching the action to an instance of alt that does not have the actions or stores bound to it which is why the store is not updating.  Lastly, if you log `alt.stores` and `alt.actions` in your test you will see that none are registered, confirming this theory.

I am afraid I do not know much about how jspm works.  I'll try looking into it more, but I figured I would let you know what the problem seems to be.

Once potential solution would be to refactor the code to be more like the [Flux Instances](https://github.com/goatslacker/alt#flux-instances) example.

**Comment by jabhishek** [comment]
Thanks jdlehman for looking into this. I will try to refactor the code as you suggested and see if it helps. I will also check with Guy Bedford if I can change my setup in some way so that the tests can work as they are. Also, if you find something else, please do let me know.

Abhi.
